### ISSUE TITLE
Unrecognized Plugin Message

### ISSUE THREAD

**Issue by lincolnmantracer** [davidsbond/vault-plugin-tailscale#16]
Hi there, I just configured the plugin for the first time. I'm getting a 500 when I try to use it, though:

```
$ vault secrets enable -path=tailscale tailscale
Success! Enabled the tailscale secrets engine at: tailscale/
$ vault read tailscale/config
Error reading tailscale/config: Error making API request.

URL: GET https://vault/v1/tailscale/config
Code: 500. Errors:

* 1 error occurred:
	* Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```

I don't see anything else in the logs. My environment is a bit weird (running inside a container, in google cloud run) but it's hard to tell if that's the cause.

**Comment by davidsbond** [comment]
Hey, thanks for raising this.

Can you tell me:

1) Which version of the plugin you are using 
2) Which version of vault are you using? 
3) What were your steps to install the plugin

I'll attempt to reproduce

**Comment by lincolnmantracer** [comment]
I'm on `0.1.2` and `v1.10.1`, respectively. I thought the issue might be related to [resolving vault itself](https://github.com/sethvargo/vault-secrets-gen/issues/2), but adding `api_addr` doesn't seem to fix the problem.

**Comment by davidsbond** [comment]
I realise now that the steps in the readme assume you've placed the binary within your Vault instance's plugin directory, but don't say to. Can you confirm you've done that?

**Comment by lincolnmantracer** [comment]
My dockerfile looks like the following:

```
# syntax = docker/dockerfile:1.3

FROM debian:buster as builder
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y wget unzip
RUN wget -q https://releases.hashicorp.com/vault/1.10.0/vault_1.10.0_linux_amd64.zip
RUN unzip vault_1.10.0_linux_amd64.zip

FROM alpine:latest as certs
RUN apk --update add ca-certificates

FROM golang:alpine as plugins
WORKDIR $GOPATH/src/<censored>
COPY . .

RUN rm -rf build
RUN go mod verify
RUN mkdir /plugins
RUN --mount=type=cache,mode=0755,target=/root/.cache/go-build \
    GOARCH=amd64 GOOS=linux CGO_ENABLED=0 go build -v -buildvcs=false -o /plugins/tailscale github.com/davidsbond/vault-plugin-tailscale
RUN chmod -R 700 /plugins

# The output container.
FROM ubuntu
COPY ./tf/config/vault.hcl .
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

# You need the SHA of a plugin to register it with vault. To do that, change
# 'scratch' to 'ubuntu' and run (for example):
#   docker build -t vault-ubuntu -f Dockerfile.vault .
#   docker run -it --entrypoint sha256sum vault-ubuntu /plugins/tailscale
COPY --from=plugins /plugins/ /plugins/
COPY --from=builder /vault .
ENTRYPOINT ["/vault", "server", "-config", "/vault.hcl"]
```

With vault.hcl as:

```
default_max_request_duration = "90s"
disable_clustering           = true
disable_mlock                = true
ui                           = true
plugin_directory             = "/plugins"
// Needed for plugins.
api_addr = "https://127.0.0.1:8200"

listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_disable = "true"
}
...
```

I know it is finding the file, because I got the sha wrong once, and it complained (at the `enable` step).

**Comment by lincolnmantracer** [comment]
Aha! Fixed it. I had `api_addr` set to an HTTPS url, but the listener is on HTTP (since google terminates https for me). Crazy that there's no logging or anything to help narrow it down.

Maybe worth adding a note to the README (even though this is vault's fault for sure).

**Comment by davidsbond** [comment]
Ah, good to hear @lincolnmantracer. I'll see about adding a gotchas section to the README. It might also be worth raising this on the Vault repo to see if they can improve the logging somehow.

**Comment by lincolnmantracer** [comment]
Great, thanks for taking a look so quickly, and sorry for the false alarm!
