### ISSUE TITLE
Generated Key Options - Documentation

### ISSUE THREAD

**Issue by luke3butler** [davidsbond/vault-plugin-tailscale#50]
I'd like the ability to create ephemeral keys using this plugin.

I'm not a Go programmer, but looking at the source it seems like there's the ability to customize `tags` and `preauthorized`.

Are ephemeral keys not a current capability right now, and how would I go about using the current customizations for keys?

**Comment by davidsbond** [comment]
Hey @luke3butler, ephemeral keys are not currently supported but I can add that pretty easily at some point this week. 

As far as using the current customisation options, you just specify the key/value pairs when you use the `vault read` command IIRC. Like so:

```
vault read secret/mysecret key=value
```

Where the `key` would be the name of the field you want to set. I can add some better documentation as part of the change I make for ephemeral keys. I initially created this plugin for minimal customisation and single use keys.
