### ISSUE TITLE
Version 0.2.3 doesn't work with current tailscale

### ISSUE THREAD

**Issue by barskern** [davidsbond/vault-plugin-tailscale#59]
Because `expirySeconds` was moved in [this commit](https://github.com/tailscale/tailscale-client-go/commit/2b0c25ac47da7ffe0c11a9e862cb4aad454ece56), the current released version doesn't work. I've set it up and I'm currently getting the following error:

```
Error reading tailscale/key: Error making API request.

URL: GET https://servie.home.iruud.cloud:8200/v1/tailscale/key
Code: 500. Errors:

* 1 error occurred:
	* json: unknown field "expirySeconds" (400)
```

This update has already been merged on the master branch, so if a new version could be released that should fix it. I will move to use the master branch for now.

**Comment by davidsbond** [comment]
I've just released v0.2.4, so please give that a go! Thanks for raising!
