### ISSUE TITLE
Is this compatible with HCP Vault?

### ISSUE THREAD

**Issue by KamalAman** [davidsbond/vault-plugin-tailscale#60]
Is this compatible with Hashicorp Cloud Platform https://portal.cloud.hashicorp.com/

How do I install the plugin?

**Comment by davidsbond** [comment]
Hey @KamalAman, I actually don't know how HCP Vault handles third party plugins. Luckily I work at HashiCorp so I'll ask someone and get back to you!

**Comment by davidsbond** [comment]
Hello again, for now there is no third party support for plugins in HCP Vault. However, the team are beginning to look into supporting this for the ones that HashiCorp themselves maintain. Unfortunately for now you won't be able to use this plugin with HCP Vault!

**Comment by KamalAman** [comment]
Sounds good, hopefully HCP Vault add some plugin support soon.
